apiVersion: v1
kind: Pod
metadata:
  name: cp-bdd-masset
  labels:
    app: cp-bdd-masset
spec:
  containers:
  - name: cp-bdd-masset
    image: anthonymasset/codepostal-mysql:latest
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: motdepassesecret
    ports:
      - containerPort: 3306
    volumeMounts:
      - name: mysql-data-masset
        mountPath: /var/lib/mysql
  volumes:
  - name: mysql-data-masset
    hostPath:
      path: /home/m1dev/masset/mysql-data
      type: DirectoryOrCreate
