apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-php-masset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cp-php-masset
  template:
    metadata:
      labels:
        app: cp-php-masset
    spec:
      containers:
        - name: cp-php-masset
          image: anthonymasset/codepostal-php:latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: service-cp-bdd-masset
            - name: DB_NAME
              value: cp
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bdd-password-mkeith495
                  key: password
          ports:
            - name: http
              containerPort: 80
